
```{r}
#question 1a
#give a matrix from 1 to 20 to x
x<-c(1:20)
x
```

```{r}
#question 1b
#give a matrix from 20 to 1 to x
x<-c(20:1)
x
```

```{r}
#question 1c
#give a matrix from 1:20 and 20 :1 to x
x<-c(1:20,20:1)
x
```

```{r}

#question 1d
#give a matrix (4,6,3) to tmp
tmp<-c(4, 6, 3)	

```

```{r}
#question 1e
#give (4,6,3) to x
y=c(4,6,3)
#give repeated y for 10 times to x
x<-rep(y,10)
x
```

```{r}
#question 1f
#give (4,6,3) which covers 31 space of length
x<-rep(c(4,6,3),each=1,len=31)
x
```

```{r}
#question 1g
#(4,6,3), 4 repeated 10 times, 6 repeated 20 times, and 3 repeated 30 times 
x<-rep(c(4,6,3),c(10,20,30))
x
```

```{r}
#question 2
#give the sequence from 3 to 6 by each step of 0.1
tmp<-seq(3,6, by=.1)
#exponential of the tmp times cosine tmp
exp(tmp)*cos(tmp)
```

```{r}
#question 3a
# give a sequence to tmp1 and tmp2
tmp1<-seq(3,36,3)
tmp2<-seq(1,34,3)
#set the matrix as 0.1 to power of tmp1 times 0.2 to the power of tmp2
c(.1**tmp1*.2**tmp2)
```

```{r}
#question 3b
# give a sequence to tmp1 and tmp2
tmp1<-seq(1,25,1)
tmp2<-seq(1,25,1)
#set the matrix as 2 to the power of tmp1/tmp2
c(2**tmp1/tmp2)
```

```{r}
#question 4a
#give a sequence to tmp3
tmp3<-seq(10, 100,1)
#sum of tmp3 to the thrid power and 4 times tmp3 to second power
sum(tmp3**3+4*tmp3**2)

```

```{r}
#question 4b
#give sequence to i
i<-seq(1,25,1)
#sum of 2 to ith power divided by i plus 3 to ith power divided by i to the second power
sum(2**i/i+3**i/(i**2))
```

```{r}
#question 5a
paste("label", 1:30, sep=" ")
#label plus 1 to 30 separated by " "
```

```{r}
#question 5b
paste("label", 1:30, sep="")
#label plus 1 to 30 separated by ""
```

```{r}
#question 6a
set.seed(50)
#set the star for seed and give x and y vectors 250 values at random
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
#y2-x1,y3-x2...
c(yVec[2:250]-xVec[1:249])
```

```{r}
#question 6b
set.seed(50)
#set the star for seed and give x and y vectors 250 values at random
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
#(sin(y1)/sin(x2),sin(y2)/sin(x3)...
c(sin(yVec[1:249])/cos(xVec[2:250]))
```

```{r}
#question 6c
set.seed(50)#set the star for seed and give x and y vectors 250 values at random
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
#(x1+2x2+x3,x2+2x3+x4,...)
c(xVec[1:248]+2*xVec[2:249]-xVec[3:250])
```

```{r}
#question 6d
set.seed(50)#set the star for seed and give x and y vectors 250 values at random
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
#sum of exp(x2/x1+10)
sum(exp(-xVec[2:250])/(xVec[1:249]+10))
```

```{r}
#question 7a
#Pick	out	the	values	in	yVec	which	are	>	600
yVec[yVec>600]
```

```{r}
#question 7b
#	find index	positions	in	yVec	of	the	values	which	are	>	600 by match #function
match(yVec[yVec>600],yVec)
```

```{r}
#question 7c
# find the values	in	xVec	which	correspond	to	the	values	in	yVec	
#which	are	>	600, and they have the same index.
xVec[yVec>600]
```

```{r}
#question 7d
#(	|x1 ???	xbar|^1/2,	|x2 ???	xbar|^1/2,	.	.	.	,	|xn ???	xbar|^1/2)	where	xbar
#denotes	the	mean	of	the	vector xbar	=	(x1,x2,...,xn).
c(sqrt((abs(xVec[1:250]-mean(xVec)))))
```

```{r}
#question 7e
#determine how	many	values	in	yVec	are	within	200	of	the	maximum	value	of	#the	terms	in	yVec
sum( yVec>(max(yVec)-200) )
```

```{r}
#question 7f
#determine how	many	numbers	in	xVec	are	divisible	by	2
sum(xVec%%2==0)
```

```{r}
#question 7g
#Sort	the	numbers	in	the	vector	xVec	in	the	order	of	increasing	values	
#in	yVec.
xVec[order(yVec)]
```

```{r}
#question 7h
#The first vector is picked, second was skipped, and thrid was skipped, and so on
 yVec[c(T,F,F)]
```

```{r}
#question 8
#give 2:38 to numerator and 3:39 to denominator
numerator<-c(2:38)
denominator<-c(3:39)
#sum of cummulative product of numerator with odd number skipped and 
#denominator with even number skipped, plus 1
sum(cumprod(numerator[c(T,F)])/cumprod(denominator[c(T,F)]),1)
```

```{r}

```

















