---
title: "510hw_5"
output: html_document
---
data(diamonds)
attributes(diamonds)
data.frame(diamonds)
```{r}
#question 1
function1<-function(x){
print(str(x))
print(ncol(x))
print(methods(class="data.frame"))
}

```

```{r}
#question 2
function2<-function(x)
{
nrow(x)
}
```

```{r}
#question 3
function3<-function(x){
colnames(x)
}
```

```{r}
#question 4
function4<-function(x){
lapply(x, class)
}
```

```{r}
#question 5
function5<-function(x)
  {
for( i in 1:10)
  if (is.numeric(x[2,i]))
    print(as.matrix(colMeans(x[i])))
  }
 
```

```{r}
#question 6
function6<-function(x){
numbers<-c(1:10)
a<-colnames(x)
for (i in numbers)
{str(count(x,vars=a[i]))}
}
```

```{r}
#question 7
#count how many rows with NA with setting 0 as NA
function7<-function(x){
nacount1=0
x[x==0]<-NA
for (i in 1:nrow(x))
 
  {if (is.na(x[i,1:ncol(x)]))
      {nacount1=nacount1+1
      }}
print(nacount1)


nacount2=0
x[x==0]<-NA
for (i in 1:nrow(x))
  for (j in 1:ncol(x))
   {if (is.na(x[i,j]))
      {nacount2=nacount2+1
      break}}
print(nacount2)
print(nacount2/nrow(x))
}
```


```{r}
#question 8

```



```{r}
#question 8
function8<-function(x){
for (i in 1:(ncol(x)-1)){
  for(j in (i+1):ncol(x) ){
    pairs=matrix(paste(colnames(x)[i],colnames(x)[j],sep="-"),ncol=1,nrow(x))
    pairs2=matrix(paste(matrix(x[,i],ncol=1,nrow=nrow(x)),matrix(x[,j],ncol=1,nrow=nrow(x)),sep="-"),ncol=1,nrow=nrow(x))
    print(data.frame(pairs,pairs2))
  }}
for (i in 1:(ncol(x)-1))
  for(j in (i+1):ncol(x)) 
    if (is.numeric(x[,i]) & is.numeric(x[,j]))
       print(paste(colnames(x)[i],colnames(x)[j],cor(x[,i],x[,j]),sep="-"))
}
```



```{r}

for (i in 1:9)
  for(j in (i+1):10 )
    if (is.numeric(diamonds[,i]) & is.numeric(diamonds[,j]))
    print(paste(colnames(diamonds)[i],colnames(diamonds)[j],cor(diamonds[,i],diamonds[,j]),sep="-"))
   
```


print(paste(colnames(diamonds)[i],colnames(diamonds)[j],cor(diamonds[,i],diamonds[,j])))





xmatrix=matrix(1,nrow=nrow(diamonds),ncol=ncol(diamonds))

xmatrix


 



